export const gbpLocation = {
  storeName: "Castle Heights Cannabis",
  domain: "www.castleheightscannabis.ca",
  city: "Ottawa",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-ottawa",
  address: "605 Center St, Ottawa, ON K1K 2N8",
  streetAddress: "605 Center St",
  postalCode: "K1K 2N8",
  phone: "(343) 308-9488",
  phoneIntl: "+13433089488",
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Accessories",
  ],
  hours: ["Open 24 Hours"],
  seoTitle: "Castle Heights Cannabis | Weed Dispensary in Ottawa",
  metaDescription: "Castle Heights Cannabis is a local weed dispensary in Ottawa offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
} as const;
